### ISSUE TITLE
ActivityType.Streamingの挙動が変わったことによりactivitiesが変になっている

### ISSUE THREAD

**Issue by Mogyuchi** [InkoHX/sm-discord-bot#127]

**Comment by InkoHX** [comment]
余裕できたら直しておこうと思います。それまでの間Twitchで配信してもらいますw

**Comment by Mogyuchi** [comment]
@InkoHX 
変更先文言提案していただければ拾いますよ

**Comment by InkoHX** [comment]
@Mogyuchi ありがとうございます！ボットもカスタムステータス使えるようになったみたいなんで、ステータスメッセージそのままで`ActivityType.CUSTOM`にしましょうか。
