### ISSUE TITLE
ArrayBuffer関連のオブジェクトについてinspect関数が期待される動作をしない

### ISSUE THREAD

**Issue by vewz** [InkoHX/sm-discord-bot#17]
![769E605A-BCE0-4554-8B58-89C55C8203DD](https://user-images.githubusercontent.com/79582228/189852786-179c8edc-27f9-4ea0-bd12-05f5bea8a908.jpeg)
![4476C925-39A2-4828-BEE9-962451023058](https://user-images.githubusercontent.com/79582228/189852796-91deee87-2dbe-436b-b074-a4093f54566f.jpeg)
![E0C12FA1-1BC5-466D-B1CF-64E31815B827](https://user-images.githubusercontent.com/79582228/189852804-0aa71676-450a-4eea-b254-7eb5c43daa63.jpeg)

**Comment by InkoHX** [comment]
inspect関数の大部分は`object-inspect`によるものなので、原因はそれにありそうです。
Node.jsの`node:util`にある`inspect`を組み込めればいいんですがね...
