### ISSUE TITLE
Bug when i run the first cmd

### ISSUE THREAD

**Issue by motikolorado** [InkoHX/sm-discord-bot#44]
> sm-discord-bot@1.1.0 prepare
> is-ci || husky install

sh: 1: is-ci: not found
sh: 1: husky: not found
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.2.0
npm notice Run npm install -g npm@9.2.0 to update!
npm notice 
npm ERR! code 127
npm ERR! path /workspaces/sm-discord-bot
npm ERR! command failed
npm ERR! command sh -c -- is-ci || husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/2022-12-31T14_18_50_096Z-debug-0.log

**Comment by InkoHX** [comment]
Try using the `--ignore-scripts` option when running `npm install` or `npm ci`

https://docs.npmjs.com/cli/v8/commands/npm-ci?v=true#ignore-scripts
